// Generated by https://quicktype.io

export interface Car {
    id:            number;
    title:         string;
    backgroundImg: string;
    description:   string;
    price:         number;
    inStock:       boolean;
    highlights:    string[];
    quantity:      number;
    ref:           null;
}
